// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/LinkedLoadMsg.proto

package cn.kang.common.protobuf.pb;

public final class LinkedLoadMsgProto {
  private LinkedLoadMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LinkedLoadMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LinkedLoadMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 server_id = 1;</code>
     *
     * <pre>
     *服务器id
     * </pre>
     */
    boolean hasServerId();
    /**
     * <code>optional int32 server_id = 1;</code>
     *
     * <pre>
     *服务器id
     * </pre>
     */
    int getServerId();

    /**
     * <code>optional string server_name = 2;</code>
     *
     * <pre>
     *服务器名称
     * </pre>
     */
    boolean hasServerName();
    /**
     * <code>optional string server_name = 2;</code>
     *
     * <pre>
     *服务器名称
     * </pre>
     */
    String getServerName();
    /**
     * <code>optional string server_name = 2;</code>
     *
     * <pre>
     *服务器名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    /**
     * <code>optional int32 load = 3;</code>
     *
     * <pre>
     *服务器的负载
     * </pre>
     */
    boolean hasLoad();
    /**
     * <code>optional int32 load = 3;</code>
     *
     * <pre>
     *服务器的负载
     * </pre>
     */
    int getLoad();

    /**
     * <code>optional string address = 4;</code>
     *
     * <pre>
     *ip地址
     * </pre>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 4;</code>
     *
     * <pre>
     *ip地址
     * </pre>
     */
    String getAddress();
    /**
     * <code>optional string address = 4;</code>
     *
     * <pre>
     *ip地址
     * </pre>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional int32 port = 5;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 5;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    int getPort();

    /**
     * <code>optional string user_server_name = 6;</code>
     *
     * <pre>
     *玩家注册的中文站点名称
     * </pre>
     */
    boolean hasUserServerName();
    /**
     * <code>optional string user_server_name = 6;</code>
     *
     * <pre>
     *玩家注册的中文站点名称
     * </pre>
     */
    String getUserServerName();
    /**
     * <code>optional string user_server_name = 6;</code>
     *
     * <pre>
     *玩家注册的中文站点名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserServerNameBytes();

    /**
     * <code>optional int32 type = 7;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 7;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    int getType();

    /**
     * <code>optional int32 connTimes = 8;</code>
     *
     * <pre>
     *连接次数
     * </pre>
     */
    boolean hasConnTimes();
    /**
     * <code>optional int32 connTimes = 8;</code>
     *
     * <pre>
     *连接次数
     * </pre>
     */
    int getConnTimes();

    /**
     * <code>optional int32 index = 9;</code>
     */
    boolean hasIndex();
    /**
     * <code>optional int32 index = 9;</code>
     */
    int getIndex();
  }
  /**
   * Protobuf type {@code LinkedLoadMsg}
   *
   * <pre>
   *服务器负载
   * </pre>
   */
  public static final class LinkedLoadMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LinkedLoadMsg)
      LinkedLoadMsgOrBuilder {
    // Use LinkedLoadMsg.newBuilder() to construct.
    private LinkedLoadMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LinkedLoadMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LinkedLoadMsg defaultInstance;
    public static LinkedLoadMsg getDefaultInstance() {
      return defaultInstance;
    }

    public LinkedLoadMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LinkedLoadMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              serverName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              load_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              address_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              port_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              userServerName_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              type_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              connTimes_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              index_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LinkedLoadMsgProto.internal_static_LinkedLoadMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LinkedLoadMsgProto.internal_static_LinkedLoadMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LinkedLoadMsg.class, Builder.class);
    }

    public static com.google.protobuf.Parser<LinkedLoadMsg> PARSER =
        new com.google.protobuf.AbstractParser<LinkedLoadMsg>() {
      public LinkedLoadMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LinkedLoadMsg(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<LinkedLoadMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVER_ID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <code>optional int32 server_id = 1;</code>
     *
     * <pre>
     *服务器id
     * </pre>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 server_id = 1;</code>
     *
     * <pre>
     *服务器id
     * </pre>
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int SERVER_NAME_FIELD_NUMBER = 2;
    private Object serverName_;
    /**
     * <code>optional string server_name = 2;</code>
     *
     * <pre>
     *服务器名称
     * </pre>
     */
    public boolean hasServerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string server_name = 2;</code>
     *
     * <pre>
     *服务器名称
     * </pre>
     */
    public String getServerName() {
      Object ref = serverName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string server_name = 2;</code>
     *
     * <pre>
     *服务器名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      Object ref = serverName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOAD_FIELD_NUMBER = 3;
    private int load_;
    /**
     * <code>optional int32 load = 3;</code>
     *
     * <pre>
     *服务器的负载
     * </pre>
     */
    public boolean hasLoad() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 load = 3;</code>
     *
     * <pre>
     *服务器的负载
     * </pre>
     */
    public int getLoad() {
      return load_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private Object address_;
    /**
     * <code>optional string address = 4;</code>
     *
     * <pre>
     *ip地址
     * </pre>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string address = 4;</code>
     *
     * <pre>
     *ip地址
     * </pre>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 4;</code>
     *
     * <pre>
     *ip地址
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private int port_;
    /**
     * <code>optional int32 port = 5;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 port = 5;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    public int getPort() {
      return port_;
    }

    public static final int USER_SERVER_NAME_FIELD_NUMBER = 6;
    private Object userServerName_;
    /**
     * <code>optional string user_server_name = 6;</code>
     *
     * <pre>
     *玩家注册的中文站点名称
     * </pre>
     */
    public boolean hasUserServerName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string user_server_name = 6;</code>
     *
     * <pre>
     *玩家注册的中文站点名称
     * </pre>
     */
    public String getUserServerName() {
      Object ref = userServerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userServerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_server_name = 6;</code>
     *
     * <pre>
     *玩家注册的中文站点名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserServerNameBytes() {
      Object ref = userServerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userServerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 7;
    private int type_;
    /**
     * <code>optional int32 type = 7;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 type = 7;</code>
     *
     * <pre>
     *端口
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int CONNTIMES_FIELD_NUMBER = 8;
    private int connTimes_;
    /**
     * <code>optional int32 connTimes = 8;</code>
     *
     * <pre>
     *连接次数
     * </pre>
     */
    public boolean hasConnTimes() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 connTimes = 8;</code>
     *
     * <pre>
     *连接次数
     * </pre>
     */
    public int getConnTimes() {
      return connTimes_;
    }

    public static final int INDEX_FIELD_NUMBER = 9;
    private int index_;
    /**
     * <code>optional int32 index = 9;</code>
     */
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 index = 9;</code>
     */
    public int getIndex() {
      return index_;
    }

    private void initFields() {
      serverId_ = 0;
      serverName_ = "";
      load_ = 0;
      address_ = "";
      port_ = 0;
      userServerName_ = "";
      type_ = 0;
      connTimes_ = 0;
      index_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getServerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, load_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, port_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUserServerNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, type_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, connTimes_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, index_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getServerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, load_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, port_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUserServerNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, type_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, connTimes_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, index_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static LinkedLoadMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LinkedLoadMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LinkedLoadMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LinkedLoadMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LinkedLoadMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static LinkedLoadMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static LinkedLoadMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static LinkedLoadMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static LinkedLoadMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static LinkedLoadMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(LinkedLoadMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LinkedLoadMsg}
     *
     * <pre>
     *服务器负载
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LinkedLoadMsg)
        LinkedLoadMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LinkedLoadMsgProto.internal_static_LinkedLoadMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LinkedLoadMsgProto.internal_static_LinkedLoadMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LinkedLoadMsg.class, Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.LinkedLoadMsgProto.LinkedLoadMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        load_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        userServerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        connTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        index_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LinkedLoadMsgProto.internal_static_LinkedLoadMsg_descriptor;
      }

      public LinkedLoadMsg getDefaultInstanceForType() {
        return LinkedLoadMsg.getDefaultInstance();
      }

      public LinkedLoadMsg build() {
        LinkedLoadMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LinkedLoadMsg buildPartial() {
        LinkedLoadMsg result = new LinkedLoadMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverName_ = serverName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.load_ = load_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.userServerName_ = userServerName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.connTimes_ = connTimes_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.index_ = index_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LinkedLoadMsg) {
          return mergeFrom((LinkedLoadMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LinkedLoadMsg other) {
        if (other == LinkedLoadMsg.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasServerName()) {
          bitField0_ |= 0x00000002;
          serverName_ = other.serverName_;
          onChanged();
        }
        if (other.hasLoad()) {
          setLoad(other.getLoad());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000008;
          address_ = other.address_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasUserServerName()) {
          bitField0_ |= 0x00000020;
          userServerName_ = other.userServerName_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasConnTimes()) {
          setConnTimes(other.getConnTimes());
        }
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LinkedLoadMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LinkedLoadMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverId_ ;
      /**
       * <code>optional int32 server_id = 1;</code>
       *
       * <pre>
       *服务器id
       * </pre>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 server_id = 1;</code>
       *
       * <pre>
       *服务器id
       * </pre>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>optional int32 server_id = 1;</code>
       *
       * <pre>
       *服务器id
       * </pre>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 server_id = 1;</code>
       *
       * <pre>
       *服务器id
       * </pre>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private Object serverName_ = "";
      /**
       * <code>optional string server_name = 2;</code>
       *
       * <pre>
       *服务器名称
       * </pre>
       */
      public boolean hasServerName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string server_name = 2;</code>
       *
       * <pre>
       *服务器名称
       * </pre>
       */
      public String getServerName() {
        Object ref = serverName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string server_name = 2;</code>
       *
       * <pre>
       *服务器名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string server_name = 2;</code>
       *
       * <pre>
       *服务器名称
       * </pre>
       */
      public Builder setServerName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string server_name = 2;</code>
       *
       * <pre>
       *服务器名称
       * </pre>
       */
      public Builder clearServerName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string server_name = 2;</code>
       *
       * <pre>
       *服务器名称
       * </pre>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serverName_ = value;
        onChanged();
        return this;
      }

      private int load_ ;
      /**
       * <code>optional int32 load = 3;</code>
       *
       * <pre>
       *服务器的负载
       * </pre>
       */
      public boolean hasLoad() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 load = 3;</code>
       *
       * <pre>
       *服务器的负载
       * </pre>
       */
      public int getLoad() {
        return load_;
      }
      /**
       * <code>optional int32 load = 3;</code>
       *
       * <pre>
       *服务器的负载
       * </pre>
       */
      public Builder setLoad(int value) {
        bitField0_ |= 0x00000004;
        load_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 load = 3;</code>
       *
       * <pre>
       *服务器的负载
       * </pre>
       */
      public Builder clearLoad() {
        bitField0_ = (bitField0_ & ~0x00000004);
        load_ = 0;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>optional string address = 4;</code>
       *
       * <pre>
       *ip地址
       * </pre>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string address = 4;</code>
       *
       * <pre>
       *ip地址
       * </pre>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string address = 4;</code>
       *
       * <pre>
       *ip地址
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 4;</code>
       *
       * <pre>
       *ip地址
       * </pre>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 4;</code>
       *
       * <pre>
       *ip地址
       * </pre>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 4;</code>
       *
       * <pre>
       *ip地址
       * </pre>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>optional int32 port = 5;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 port = 5;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 5;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000010;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 5;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        port_ = 0;
        onChanged();
        return this;
      }

      private Object userServerName_ = "";
      /**
       * <code>optional string user_server_name = 6;</code>
       *
       * <pre>
       *玩家注册的中文站点名称
       * </pre>
       */
      public boolean hasUserServerName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string user_server_name = 6;</code>
       *
       * <pre>
       *玩家注册的中文站点名称
       * </pre>
       */
      public String getUserServerName() {
        Object ref = userServerName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userServerName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string user_server_name = 6;</code>
       *
       * <pre>
       *玩家注册的中文站点名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserServerNameBytes() {
        Object ref = userServerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userServerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_server_name = 6;</code>
       *
       * <pre>
       *玩家注册的中文站点名称
       * </pre>
       */
      public Builder setUserServerName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userServerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_server_name = 6;</code>
       *
       * <pre>
       *玩家注册的中文站点名称
       * </pre>
       */
      public Builder clearUserServerName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        userServerName_ = getDefaultInstance().getUserServerName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_server_name = 6;</code>
       *
       * <pre>
       *玩家注册的中文站点名称
       * </pre>
       */
      public Builder setUserServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userServerName_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 7;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 type = 7;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 7;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 7;</code>
       *
       * <pre>
       *端口
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        onChanged();
        return this;
      }

      private int connTimes_ ;
      /**
       * <code>optional int32 connTimes = 8;</code>
       *
       * <pre>
       *连接次数
       * </pre>
       */
      public boolean hasConnTimes() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 connTimes = 8;</code>
       *
       * <pre>
       *连接次数
       * </pre>
       */
      public int getConnTimes() {
        return connTimes_;
      }
      /**
       * <code>optional int32 connTimes = 8;</code>
       *
       * <pre>
       *连接次数
       * </pre>
       */
      public Builder setConnTimes(int value) {
        bitField0_ |= 0x00000080;
        connTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 connTimes = 8;</code>
       *
       * <pre>
       *连接次数
       * </pre>
       */
      public Builder clearConnTimes() {
        bitField0_ = (bitField0_ & ~0x00000080);
        connTimes_ = 0;
        onChanged();
        return this;
      }

      private int index_ ;
      /**
       * <code>optional int32 index = 9;</code>
       */
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 index = 9;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>optional int32 index = 9;</code>
       */
      public Builder setIndex(int value) {
        bitField0_ |= 0x00000100;
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 index = 9;</code>
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000100);
        index_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LinkedLoadMsg)
    }

    static {
      defaultInstance = new LinkedLoadMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LinkedLoadMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LinkedLoadMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LinkedLoadMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032common/LinkedLoadMsg.proto\"\256\001\n\rLinkedL" +
      "oadMsg\022\021\n\tserver_id\030\001 \001(\005\022\023\n\013server_name" +
      "\030\002 \001(\t\022\014\n\004load\030\003 \001(\005\022\017\n\007address\030\004 \001(\t\022\014\n" +
      "\004port\030\005 \001(\005\022\030\n\020user_server_name\030\006 \001(\t\022\014\n" +
      "\004type\030\007 \001(\005\022\021\n\tconnTimes\030\010 \001(\005\022\r\n\005index\030" +
      "\t \001(\005B6\n com.chuangyou.common.protobuf.p" +
      "bB\022LinkedLoadMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LinkedLoadMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LinkedLoadMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LinkedLoadMsg_descriptor,
        new String[] { "ServerId", "ServerName", "Load", "Address", "Port", "UserServerName", "Type", "ConnTimes", "Index", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
